# Generated by Django 4.1.6 on 2023-02-13 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('car_number', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='./images/car/')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserX',
            fields=[
                ('userx_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Prefer Not to Say')], max_length=50)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(blank=True, choices=[('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Employed', 'Unemployed')], default='Unemployed', max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=0)),
                ('description', models.CharField(max_length=250)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.userx')),
            ],
            options={
                'unique_together': {('car_id', 'user_id')},
            },
        ),
    ]
