# Generated by Django 4.1.7 on 2023-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0005_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(upload_to="images/car"),
        ),
    ]
