# Generated by Django 4.1.7 on 2023-02-19 19:25

import django.core.validators
from django.db import migrations, models
import rental.validators


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0006_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(
                choices=[
                    ("Ford", "Ford"),
                    ("Vauxhall", "Vauxhall"),
                    ("Volkswagen", "Volkswagen"),
                    ("BMW", "BMW"),
                    ("Audi", "Audi"),
                    ("Mercedes-Benz", "Mercedes-Benz"),
                    ("Toyota", "Toyota"),
                    ("Nissan", "Nissan"),
                    ("Peugeot", "Peugeot"),
                    ("Renault", "Renault"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="mileage",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveSmallIntegerField(
                validators=[rental.validators.year_validator]
            ),
        ),
    ]
