# Generated by Django 4.1.7 on 2023-02-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0009_car_dscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="dscription",
            new_name="description",
        ),
    ]
