# Generated by Django 4.1.7 on 2023-02-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0010_rename_dscription_car_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(
                default="images/customer/default.png", upload_to="images/customer"
            ),
        ),
    ]
