# Generated by Django 4.1.7 on 2023-02-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0011_customer_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                default="images/car/default.jpeg", upload_to="images/car"
            ),
        ),
    ]
