# Generated by Django 4.1.7 on 2023-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0012_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Prefer Not to Say", "Prefer Not to Say"),
                ],
                max_length=50,
            ),
        ),
    ]
