# Generated by Django 4.1.7 on 2023-02-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0014_renthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
