# Generated by Django 4.1.7 on 2023-02-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0018_alter_renthistory_returned_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="car_id",
            new_name="car",
        ),
        migrations.RenameField(
            model_name="reviews",
            old_name="user_id",
            new_name="customer",
        ),
        migrations.AlterUniqueTogether(
            name="reviews",
            unique_together={("customer", "car")},
        ),
    ]
