# Generated by Django 4.1.7 on 2023-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0020_alter_reviews_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
