# Generated by Django 4.1.7 on 2023-02-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalForEmployee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_pic",
            field=models.ImageField(
                default="images/employee/default.png", upload_to="images/employee"
            ),
        ),
    ]
