# Generated by Django 4.1.7 on 2023-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalForEmployee", "0002_employee_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
